// angular/src/app/app.component.ts
import { Component } from '@angular/core';
import { FormsModule } from '@angular/forms';

@Component({
  standalone: true,
  selector: 'app-root',
  template: `
    <main>
      <h1>Hi, please enter your name:</h1>
      <p>First: <input [(ngModel)]="firstName" /></p>
      <p>Last: <input [(ngModel)]="lastName" /></p>
      <p>{{ firstName }} {{ lastName }}</p>
      <p><button (click)="reset()">Reset</button></p>
    </main>
  `,
  imports: [
    FormsModule
  ]
})
export class AppComponent {
  firstName = '';
  lastName = '';

  reset() {
    this.firstName = '';
    this.lastName = '';
  }
}

// svelte/src/App.svelte
<script>
  let firstName = '';
  let lastName = '';

  $: fullName = firstName + ' ' + lastName;

  function reset() {
    firstName = '';
    lastName = '';
  }
</script>

<main>
  <h1>Hi, please enter your name:</h1>
  <p>First: <input bind:value={firstName} /></p>
  <p>Last: <input bind:value={lastName} /></p>
  <p>{ fullName }</p>
  <p><button on:click={reset}>Reset</button></p>
</main>
