// vuejs/src/App.vue
<template>
  <main>
    <h1>Hi, please enter your name:</h1>
    <p>First: <input v-model="firstName" /></p>
    <p>Last: <input v-model="lastName" /></p>
    <p>{{ fullName }}</p>
    <p><button v-on:click="reset">Reset</button></p>
  </main>
</template>

<script>
export default {
  data() {
    return {
      firstName: '',
      lastName: ''
    }
  },
  computed: {
    fullName() {
      return this.firstName + ' ' + this.lastName
    }
  },
  methods: {
    reset() {
      this.firstName = ''
      this.lastName = ''
    }
  }
}
</script>

// svelte/src/App.svelte
<script>
  let firstName = '';
  let lastName = '';

  $: fullName = firstName + ' ' + lastName;

  function reset() {
    firstName = '';
    lastName = '';
  }
</script>

<main>
  <h1>Hi, please enter your name:</h1>
  <p>First: <input bind:value={firstName} /></p>
  <p>Last: <input bind:value={lastName} /></p>
  <p>{ fullName }</p>
  <p><button on:click={reset}>Reset</button></p>
</main>
